AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  BlockbusterIndexMCPFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "blockbuster-index-mcp-local"
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: ../dist/mcp.zip
      Timeout: 5
      MemorySize: 128
