AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String
    Description: "The environment for the deployment (dev or prod)"
    AllowedValues:
      - dev
      - prod
    Default: dev
    ConstraintDescription: "Must be either 'dev' or 'prod'."
  S3Key:
    Type: String
    Description: The S3 key for the lambda function zip file.

Resources:
  BlockbusterIndexMCPFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "blockbuster-index-mcp-${Environment}"
      Runtime: nodejs20.x
      Role:
        Fn::ImportValue: !Sub "LambdaExecutionBlockbusterIndexMCPRole-${Environment}"
      Handler: index.handler
      Code:
        S3Bucket:
          Fn::ImportValue: !Sub "BlockbusterIndexMCPBucketName-${Environment}"
        S3Key: !Ref S3Key
      Timeout: 5
      MemorySize: 128

  MyLambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref BlockbusterIndexMCPFunction

Outputs:
  BlockbusterIndexMCPFunctionArn:
    Description: "ARN of the mcp function"
    Value: !GetAtt MyLambdaVersion.FunctionArn
    Export:
      Name: !Sub "BlockbusterIndexMCPFunctionArn-${Environment}"
